"""Data contracts and reproducibility helpers for TIDE-JEPA experiments.

This module validates caller-provided annotations; it does not discover,
download, or approve datasets on behalf of a language community.
"""

from dataclasses import dataclass
from difflib import SequenceMatcher
import hashlib
import json
import math
import os
from pathlib import Path
import random
import tempfile
import unicodedata
from typing import TYPE_CHECKING, Iterable, Mapping

from .config import LANGUAGES
from .schema import Action, Edge, EdgePath, Inventory

if TYPE_CHECKING:
    from .config import ModelConfig
    from .training import Batch


DATA_SCHEMA_VERSION = "tide-jepa-record-v1"
PAD_ID = 0
BOS_ID = 1
EOS_ID = 2
BYTE_OFFSET = 3
BYTE_VOCAB_SIZE = BYTE_OFFSET + 256
SPLIT_NAMES = ("train", "validation", "test")


class UTF8ByteTokenizer:
    """Losslessly encode NFC-normalized Unicode as UTF-8 byte token IDs.

    The fixed byte vocabulary avoids fitting a tokenizer vocabulary on a small
    corpus. It can lengthen sequences and is not a claim of linguistic quality.
    """

    pad_id = PAD_ID
    bos_id = BOS_ID
    eos_id = EOS_ID
    vocab_size = BYTE_VOCAB_SIZE

    def encode(self, text: str, *, add_bos: bool = False, add_eos: bool = False) -> list[int]:
        """Encode text, optionally adding the fixed BOS and EOS token IDs."""
        if not isinstance(text, str):
            raise TypeError("text must be a string")
        normalized = unicodedata.normalize("NFC", text)
        token_ids = [byte + BYTE_OFFSET for byte in normalized.encode("utf-8")]
        if add_bos:
            token_ids.insert(0, BOS_ID)
        if add_eos:
            token_ids.append(EOS_ID)
        return token_ids

    def decode(self, token_ids: Iterable[int], *, errors: str = "strict") -> str:
        """Decode byte IDs, allowing optional BOS/EOS and trailing padding.

        ``errors="replace"`` makes arbitrary generated byte sequences displayable;
        strict decoding remains the default for audits and validity measurements.
        """
        if errors not in {"strict", "replace"}:
            raise ValueError("errors must be strict or replace")
        byte_values = bytearray()
        padding_started = False
        for position, token_id in enumerate(token_ids):
            if type(token_id) is not int or not 0 <= token_id < BYTE_VOCAB_SIZE:
                raise ValueError("token IDs must be integers inside the byte vocabulary")
            if token_id == EOS_ID:
                break
            if token_id == PAD_ID:
                padding_started = True
                continue
            if padding_started:
                raise ValueError("padding may only appear after the text tokens")
            if token_id == BOS_ID:
                if position != 0:
                    raise ValueError("BOS is only allowed as the first token")
                continue
            byte_values.append(token_id - BYTE_OFFSET)
        text = byte_values.decode("utf-8", errors=errors)
        return unicodedata.normalize("NFC", text)


@dataclass(frozen=True)
class CorpusRecord:
    """One licensed, action-conditioned source-to-target transition."""

    record_id: str
    split_group_id: str
    language: str
    source_text: str
    target_text: str
    source_frame_id: str
    target_frame_id: str
    action: Action
    provenance_ref: str
    license_ref: str
    approval_status: str = "pending"
    path_id: str | None = None
    path_step: int | None = None

    def __post_init__(self) -> None:
        required = (
            "record_id",
            "split_group_id",
            "language",
            "source_text",
            "target_text",
            "source_frame_id",
            "target_frame_id",
            "provenance_ref",
            "license_ref",
        )
        if any(not isinstance(getattr(self, name), str) or not getattr(self, name).strip() for name in required):
            raise ValueError("record identifiers, text, frame IDs, provenance, and license are required")
        if not isinstance(self.action, Action):
            raise TypeError("action must be an Action")
        if self.approval_status not in {"pending", "approved", "rejected"}:
            raise ValueError("approval_status must be pending, approved, or rejected")
        if (self.path_id is None) != (self.path_step is None):
            raise ValueError("path_id and path_step must either both be set or both be absent")
        if self.path_id is not None and (
            not isinstance(self.path_id, str)
            or not self.path_id.strip()
            or type(self.path_step) is not int
            or self.path_step < 0
        ):
            raise ValueError("path metadata needs a nonempty path_id and a nonnegative integer step")

    def to_dict(self) -> dict[str, object]:
        """Return the canonical JSON-compatible representation of this row."""
        return {
            "schema_version": DATA_SCHEMA_VERSION,
            "record_id": self.record_id,
            "split_group_id": self.split_group_id,
            "language": self.language,
            "source_text": self.source_text,
            "target_text": self.target_text,
            "source_frame_id": self.source_frame_id,
            "target_frame_id": self.target_frame_id,
            "action": {"kind": self.action.kind, "value": self.action.value},
            "provenance_ref": self.provenance_ref,
            "license_ref": self.license_ref,
            "approval_status": self.approval_status,
            "path_id": self.path_id,
            "path_step": self.path_step,
        }


@dataclass(frozen=True)
class SplitManifest:
    """Deterministic group-level split assignment and its dataset fingerprint."""

    dataset_sha256: str
    seed: int
    fractions: Mapping[str, float]
    groups: Mapping[str, str]
    record_ids: Mapping[str, tuple[str, ...]]

    def to_dict(self) -> dict[str, object]:
        """Return a stable JSON-compatible split manifest."""
        return {
            "schema_version": "tide-jepa-split-v1",
            "dataset_sha256": self.dataset_sha256,
            "seed": self.seed,
            "fractions": {name: self.fractions[name] for name in SPLIT_NAMES},
            "groups": dict(sorted(self.groups.items())),
            "record_ids": {name: list(self.record_ids[name]) for name in SPLIT_NAMES},
        }

    @property
    def sha256(self) -> str:
        """Return a digest of the complete split assignment."""
        return hashlib.sha256(_canonical_json(self.to_dict())).hexdigest()


def validate_records(
    records: Iterable[CorpusRecord],
    inventory: Inventory,
    languages: tuple[str, ...] = LANGUAGES,
    *,
    require_approved: bool = True,
) -> tuple[CorpusRecord, ...]:
    """Validate IDs, language/action licenses, provenance, and path chains.

    ``require_approved=False`` is for metadata audits only; it is not approval
    to train on pending or rejected rows.
    """
    rows = tuple(records)
    seen_ids: set[str] = set()
    paths: dict[tuple[str, str], list[CorpusRecord]] = {}
    path_groups: dict[str, set[str]] = {}
    for record in rows:
        if not isinstance(record, CorpusRecord):
            raise TypeError("records must contain only CorpusRecord values")
        if record.record_id in seen_ids:
            raise ValueError(f"duplicate record_id: {record.record_id}")
        seen_ids.add(record.record_id)
        if record.language not in languages:
            raise ValueError(f"unconfigured language: {record.language}")
        inventory.require(record.language, record.action)
        if require_approved and record.approval_status != "approved":
            raise ValueError(f"record is not approved for use: {record.record_id}")
        if record.path_id is not None:
            paths.setdefault((record.path_id, record.language), []).append(record)
            path_groups.setdefault(record.path_id, set()).add(record.split_group_id)

    for path_id, group_ids in path_groups.items():
        if len(group_ids) != 1:
            raise ValueError(f"all language realizations of path {path_id} must share one split group")
    for (path_id, _language), path_rows in paths.items():
        ordered = sorted(path_rows, key=lambda row: row.path_step)
        if len(ordered) < 2:
            raise ValueError(f"path {path_id} must contain at least two action edges")
        steps = [row.path_step for row in ordered]
        if steps != list(range(len(ordered))):
            raise ValueError(f"path {path_id} steps must be unique and contiguous from zero")
        for current, following in zip(ordered, ordered[1:]):
            if current.target_frame_id != following.source_frame_id:
                raise ValueError(f"path {path_id} is not continuous in semantic frames")
    return rows


def read_jsonl(
    path: str | Path,
    inventory: Inventory,
    languages: tuple[str, ...] = LANGUAGES,
    *,
    require_approved: bool = True,
) -> tuple[CorpusRecord, ...]:
    """Read and validate a UTF-8 JSONL corpus without external dependencies."""
    rows: list[CorpusRecord] = []
    allowed = {
        "schema_version",
        "record_id",
        "split_group_id",
        "language",
        "source_text",
        "target_text",
        "source_frame_id",
        "target_frame_id",
        "action",
        "provenance_ref",
        "license_ref",
        "approval_status",
        "path_id",
        "path_step",
    }
    with Path(path).open("r", encoding="utf-8") as stream:
        for line_number, line in enumerate(stream, start=1):
            if not line.strip():
                continue
            try:
                value = json.loads(line)
                if not isinstance(value, dict):
                    raise ValueError("each JSONL row must be an object")
                if set(value) - allowed:
                    raise ValueError(f"unknown fields: {sorted(set(value) - allowed)}")
                if value.get("schema_version") != DATA_SCHEMA_VERSION:
                    raise ValueError("unsupported or missing schema_version")
                action_value = value.get("action")
                if not isinstance(action_value, dict) or set(action_value) != {"kind", "value"}:
                    raise ValueError("action must contain exactly kind and value")
                rows.append(
                    CorpusRecord(
                        record_id=value["record_id"],
                        split_group_id=value["split_group_id"],
                        language=value["language"],
                        source_text=value["source_text"],
                        target_text=value["target_text"],
                        source_frame_id=value["source_frame_id"],
                        target_frame_id=value["target_frame_id"],
                        action=Action(action_value["kind"], action_value["value"]),
                        provenance_ref=value["provenance_ref"],
                        license_ref=value["license_ref"],
                        approval_status=value.get("approval_status", "pending"),
                        path_id=value.get("path_id"),
                        path_step=value.get("path_step"),
                    )
                )
            except (KeyError, TypeError, ValueError, json.JSONDecodeError) as error:
                raise ValueError(f"invalid corpus row at line {line_number}: {error}") from error
    return validate_records(rows, inventory, languages, require_approved=require_approved)


def dataset_fingerprint(records: Iterable[CorpusRecord]) -> str:
    """Hash canonical records independent of input row order."""
    rows = tuple(records)
    ids = [row.record_id for row in rows]
    if len(ids) != len(set(ids)):
        raise ValueError("cannot fingerprint records with duplicate record_id values")
    digest = hashlib.sha256()
    for row in sorted(rows, key=lambda item: item.record_id):
        digest.update(_canonical_json(row.to_dict()))
        digest.update(b"\n")
    return digest.hexdigest()


def grouped_split(
    records: Iterable[CorpusRecord],
    inventory: Inventory,
    *,
    seed: int,
    train: float = 0.8,
    validation: float = 0.1,
    test: float = 0.1,
    require_approved: bool = True,
) -> SplitManifest:
    """Validate approved rows and create deterministic group-safe splits.

    Groups are the leakage boundary: translations, paraphrases, and variants
    derived from the same semantic event must share ``split_group_id``. An
    inventory is required so action licensing cannot be skipped at this gate.
    """
    rows = validate_records(records, inventory, require_approved=require_approved)
    if not rows:
        raise ValueError("cannot split an empty dataset")
    if type(seed) is not int:
        raise ValueError("seed must be an integer")
    fractions = {"train": train, "validation": validation, "test": test}
    if any(not math.isfinite(value) or value <= 0 for value in fractions.values()):
        raise ValueError("all split fractions must be finite and positive")
    if not math.isclose(sum(fractions.values()), 1.0, rel_tol=0.0, abs_tol=1e-9):
        raise ValueError("train, validation, and test fractions must sum to one")
    record_ids = [row.record_id for row in rows]
    if len(record_ids) != len(set(record_ids)):
        raise ValueError("record_id values must be unique before splitting")

    grouped: dict[str, list[CorpusRecord]] = {}
    for row in rows:
        grouped.setdefault(row.split_group_id, []).append(row)
    if len(grouped) < len(SPLIT_NAMES):
        raise ValueError("at least three independent split groups are required")

    rng = random.Random(seed)
    group_order = sorted(grouped)
    rng.shuffle(group_order)
    group_order.sort(key=lambda group_id: -len(grouped[group_id]))
    target_counts = {name: len(rows) * fractions[name] for name in SPLIT_NAMES}
    current_counts = {name: 0 for name in SPLIT_NAMES}
    split_order = sorted(SPLIT_NAMES, key=lambda name: (-fractions[name], SPLIT_NAMES.index(name)))
    group_assignment: dict[str, str] = {}
    for index, group_id in enumerate(group_order):
        if index < len(SPLIT_NAMES):
            split_name = split_order[index]
        else:
            split_name = max(
                SPLIT_NAMES,
                key=lambda name: (
                    (target_counts[name] - current_counts[name]) / target_counts[name],
                    fractions[name],
                    -SPLIT_NAMES.index(name),
                ),
            )
        group_assignment[group_id] = split_name
        current_counts[split_name] += len(grouped[group_id])

    ids_by_split = {
        name: tuple(sorted(row.record_id for row in rows if group_assignment[row.split_group_id] == name))
        for name in SPLIT_NAMES
    }
    manifest = SplitManifest(
        dataset_sha256=dataset_fingerprint(rows),
        seed=seed,
        fractions=fractions,
        groups=dict(sorted(group_assignment.items())),
        record_ids=ids_by_split,
    )
    _validate_cross_split_leakage(rows, manifest.groups)
    return manifest


def _validate_cross_split_leakage(rows, groups) -> None:
    """Apply the same frame/text leakage boundary to every split route."""
    seen_frames, seen_text = {}, {}
    for row in rows:
        split = groups[row.split_group_id]
        for frame in (row.source_frame_id, row.target_frame_id):
            if frame in seen_frames and seen_frames[frame] != split:
                raise ValueError("semantic frame occurs in multiple splits")
            seen_frames[frame] = split
        for text in (row.source_text, row.target_text):
            key = (row.language, " ".join(unicodedata.normalize("NFC", text).casefold().split()))
            if key in seen_text and seen_text[key] != split:
                raise ValueError("normalized sentence occurs in multiple splits")
            seen_text[key] = split


def write_split_manifest(path: str | Path, manifest: SplitManifest) -> None:
    """Atomically save a split manifest; importing this module writes nothing."""
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(manifest.to_dict(), ensure_ascii=False, sort_keys=True, indent=2) + "\n"
    file_descriptor, temporary_name = tempfile.mkstemp(prefix=f".{destination.name}.", dir=destination.parent)
    try:
        with os.fdopen(file_descriptor, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(payload)
        os.replace(temporary_name, destination)
    except BaseException:
        try:
            os.unlink(temporary_name)
        except FileNotFoundError:
            pass
        raise


def read_split_manifest(path: str | Path, records, inventory: Inventory) -> SplitManifest:
    """Validate a frozen assignment against the exact approved corpus.

    Also reject reuse of a frame or normalized sentence across split groups;
    this catches common annotations that would otherwise leak across splits.
    """
    rows = validate_records(records, inventory)
    with Path(path).open(encoding="utf-8") as stream:
        value = json.load(stream)
    if value.get("schema_version") != "tide-jepa-split-v1":
        raise ValueError("unsupported frozen split schema")
    if value.get("dataset_sha256") != dataset_fingerprint(rows):
        raise ValueError("frozen split corpus fingerprint differs")
    if type(value.get("seed")) is not int:
        raise ValueError("frozen split seed must be an integer")
    fractions = value.get("fractions", {})
    if set(fractions) != set(SPLIT_NAMES) or any(type(v) not in {int, float} or not math.isfinite(v) or v <= 0 for v in fractions.values()):
        raise ValueError("invalid frozen split fractions")
    if not math.isclose(sum(fractions.values()), 1.0, abs_tol=1e-9):
        raise ValueError("frozen split fractions must sum to one")
    groups = value.get("groups", {})
    if set(groups) != {r.split_group_id for r in rows} or not set(groups.values()) <= set(SPLIT_NAMES):
        raise ValueError("frozen split must assign every group exactly once")
    ids = value.get("record_ids", {})
    if set(ids) != set(SPLIT_NAMES):
        raise ValueError("frozen split needs train, validation and test")
    for name in SPLIT_NAMES:
        expected = sorted(r.record_id for r in rows if groups[r.split_group_id] == name)
        if not isinstance(ids[name], list) or sorted(ids[name]) != expected or not expected:
            raise ValueError("frozen split record IDs disagree with its groups")
    _validate_cross_split_leakage(rows, groups)
    return SplitManifest(value["dataset_sha256"], value["seed"], fractions, groups,
                         {name: tuple(sorted(ids[name])) for name in SPLIT_NAMES})


def build_batch(
    records: Iterable[CorpusRecord],
    cfg: "ModelConfig",
    inventory: Inventory,
    tokenizer: UTF8ByteTokenizer | None = None,
    *,
    device: str = "cpu",
) -> "Batch":
    """Convert approved records to the model's padded tensor batch.

    No language alignment is inferred. The returned batch contains within-
    language paths only; callers must attach separately licensed edge/path
    pairs after annotation review.
    """
    import torch

    from .training import Batch

    tokenizer = tokenizer or UTF8ByteTokenizer()
    if cfg.vocab_size != tokenizer.vocab_size or cfg.pad_id != tokenizer.pad_id or cfg.bos_id != tokenizer.bos_id:
        raise ValueError("model configuration must match the fixed byte tokenizer vocabulary and special IDs")
    rows = validate_records(records, inventory, cfg.languages)
    if len(rows) == 0:
        raise ValueError("cannot build a model batch from an empty record set")

    source_rows = [tokenizer.encode(row.source_text) for row in rows]
    target_rows = [tokenizer.encode(row.target_text, add_eos=True) for row in rows]
    for token_rows in (source_rows, target_rows):
        if any(not token_row or len(token_row) > cfg.max_length for token_row in token_rows):
            raise ValueError("encoded text is empty or exceeds the configured maximum length")

    def pad(token_rows: list[list[int]]) -> torch.Tensor:
        width = max(len(token_row) for token_row in token_rows)
        return torch.tensor(
            [token_row + [cfg.pad_id] * (width - len(token_row)) for token_row in token_rows],
            dtype=torch.long,
            device=device,
        )

    edges = tuple(
        Edge(row.language, row.source_frame_id, row.target_frame_id, row.action)
        for row in rows
    )
    action_ids = torch.tensor(
        [inventory.require(row.language, row.action) for row in rows], dtype=torch.long, device=device
    )
    language_ids = torch.tensor(
        [cfg.languages.index(row.language) for row in rows], dtype=torch.long, device=device
    )
    edge_indices: dict[tuple[str, str], list[tuple[int, int]]] = {}
    for index, row in enumerate(rows):
        if row.path_id is not None:
            edge_indices.setdefault((row.path_id, row.language), []).append((row.path_step, index))
    paths = tuple(
        EdgePath(tuple(edge_index for _step, edge_index in sorted(items)))
        for _path_key, items in sorted(edge_indices.items())
    )
    target_tensor = pad(target_rows)
    # Mark target bytes that occur in an ordered unchanged span of the source.
    # This supports an optional copy-preservation loss without exposing text in
    # logs or making any semantic claim about the changed tokens.
    copy_rows = []
    for source_tokens, target_tokens in zip(source_rows, target_rows):
        mask = [False] * len(target_tokens)
        matcher = SequenceMatcher(a=source_tokens, b=target_tokens, autojunk=False)
        for source_start, target_start, length in matcher.get_matching_blocks():
            if length:
                mask[target_start : target_start + length] = [True] * length
        copy_rows.append(mask)
    copy_width = target_tensor.shape[1]
    copy_mask = torch.tensor(
        [mask + [False] * (copy_width - len(mask)) for mask in copy_rows],
        dtype=torch.bool,
        device=device,
    )
    # Shift the padded label tensor. Short rows retain EOS in the first
    # ignored decoder position instead of losing it before batch padding.
    decoder_tensor = torch.cat((torch.full((len(rows), 1), cfg.bos_id, dtype=torch.long, device=device),
                                target_tensor[:, :-1]), dim=1)
    batch = Batch(
        source=pad(source_rows),
        target=target_tensor,
        decoder_input=decoder_tensor,
        labels=target_tensor,
        copy_mask=copy_mask,
        action_ids=action_ids,
        language_ids=language_ids,
        edges=edges,
        paths=paths,
    )
    batch.validate(cfg, inventory)
    return batch


def _canonical_json(value: object) -> bytes:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode("utf-8")
